mod ide_helper;
mod options;
mod phpstorm_meta;
mod xfcp;

use crate::contract::Contract;
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    IdeHelper,
    PhpstormMeta,
    Xfcp,
    Options,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntityMode {
    Redeclare,
    Mixin,
}

impl EntityMode {
    pub fn parse(s: &str) -> Option<EntityMode> {
        match s.trim().to_ascii_lowercase().as_str() {
            "redeclare" => Some(EntityMode::Redeclare),
            "mixin" => Some(EntityMode::Mixin),
            _ => None,
        }
    }
}

impl Target {
    pub const ALL: [Target; 4] = [
        Target::IdeHelper,
        Target::PhpstormMeta,
        Target::Xfcp,
        Target::Options,
    ];

    pub fn filename(self) -> &'static str {
        match self {
            Target::IdeHelper => "_ide_helper.php",
            Target::PhpstormMeta => ".phpstorm.meta.php",
            Target::Xfcp => "_ide_helper_xfcp.php",
            Target::Options => "_ide_helper_options.php",
        }
    }

    pub fn parse(s: &str) -> Option<Target> {
        match s.trim().to_ascii_lowercase().as_str() {
            "ide-helper" | "ide_helper" | "idehelper" => Some(Target::IdeHelper),
            "phpstorm-meta" | "phpstorm_meta" | "meta" => Some(Target::PhpstormMeta),
            "xfcp" => Some(Target::Xfcp),
            "options" => Some(Target::Options),
            _ => None,
        }
    }
}

impl fmt::Display for Target {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Target::IdeHelper => "ide-helper",
            Target::PhpstormMeta => "phpstorm-meta",
            Target::Xfcp => "xfcp",
            Target::Options => "options",
        };
        f.write_str(s)
    }
}

pub struct GeneratedFile {
    pub filename: &'static str,
    pub contents: String,
}

pub fn render(contract: &Contract, target: Target, mode: EntityMode) -> GeneratedFile {
    let contents = match target {
        Target::IdeHelper => ide_helper::render(contract, mode),
        Target::PhpstormMeta => phpstorm_meta::render(contract),
        Target::Xfcp => xfcp::render(contract),
        Target::Options => options::render(contract),
    };
    GeneratedFile {
        filename: target.filename(),
        contents,
    }
}

pub fn render_all(contract: &Contract, targets: &[Target], mode: EntityMode) -> Vec<GeneratedFile> {
    targets.iter().map(|t| render(contract, *t, mode)).collect()
}

pub(crate) fn banner(extra: &str) -> String {
    format!(
        "<?php\n\n/**\n * This file is auto-generated by xf-typegen. DO NOT EDIT.\n *\n * It exists only for static analysis (IDE autocomplete / go-to-definition).\n * It is NOT meant to be autoloaded or executed at runtime.\n{} */\n\n",
        extra
    )
}
